workflows:
  ios-workflow:
    name: Build iOS
    environment:
      xcode: latest
      flutter: stable
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
