// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAshLj57lnpGLpb7sar2TZ0xOLC4fooMfw',
    appId: '1:480454085596:web:f258942cdbd8f3fce79d19',
    messagingSenderId: '480454085596',
    projectId: 'timetree-c5cb7',
    authDomain: 'timetree-c5cb7.firebaseapp.com',
    storageBucket: 'timetree-c5cb7.firebasestorage.app',
    measurementId: 'G-7WRYJC8NP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTZCfbd7Q7yeSdt18JDqOJZ6vohMXE1Ro',
    appId: '1:480454085596:android:0837708e6d0a4d09e79d19',
    messagingSenderId: '480454085596',
    projectId: 'timetree-c5cb7',
    storageBucket: 'timetree-c5cb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQM84FKSH_sTDrMI3CaYaYAfAw-PEnQcE',
    appId: '1:480454085596:ios:03c016f8033603dbe79d19',
    messagingSenderId: '480454085596',
    projectId: 'timetree-c5cb7',
    storageBucket: 'timetree-c5cb7.firebasestorage.app',
    iosBundleId: 'com.example.timetree1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQM84FKSH_sTDrMI3CaYaYAfAw-PEnQcE',
    appId: '1:480454085596:ios:03c016f8033603dbe79d19',
    messagingSenderId: '480454085596',
    projectId: 'timetree-c5cb7',
    storageBucket: 'timetree-c5cb7.firebasestorage.app',
    iosBundleId: 'com.example.timetree1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAshLj57lnpGLpb7sar2TZ0xOLC4fooMfw',
    appId: '1:480454085596:web:f797d12f3c141587e79d19',
    messagingSenderId: '480454085596',
    projectId: 'timetree-c5cb7',
    authDomain: 'timetree-c5cb7.firebaseapp.com',
    storageBucket: 'timetree-c5cb7.firebasestorage.app',
    measurementId: 'G-H2NSMC43ZY',
  );
}
